Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 50

Metrics/ClassLength:
  Max: 200

Style/DoubleNegation:
  Enabled: false
