development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: uoftcodes_development
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: uoftcodes_test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: uoftcodes_production
  pool: 5
  username: postgres
  password: root
