development:
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>

test:
  rollbar_access_token: test_rollbar_access_token

production:
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
